name: Nix Flake Checker
description: |
  Check your `flake.lock` files for common problems like outdated Nixpkgs releases.
branding:
  icon: "box"
  color: "purple"
inputs:
  flake-lock-path:
    description: |
      The path to the `flake.lock` file you want to check.
    default: flake.lock
  condition:
    description: |
      A Common Expression Language (CEL) condition expressing your flake policy.
      Supersedes all `check-*` parameters.
    required: false
  check-outdated:
    description: |
      Whether to check that the root Nixpkgs input is less than 30 days old.
    default: true
  check-owner:
    description: |
      Whether to check that the root Nixpkgs input has the `NixOS` GitHub org as its owner.
    default: true
  check-supported:
    description: |
      Whether to check that the root Nixpkgs input has a supported Git ref. Currently supported
      refs: `nixos-22.11`, `nixos-22.11-small`, `nixos-23.05`, `nixos-23.05-small`, `nixos-unstable`,
      `nixos-unstable-small`, `nixpkgs-22.11-darwin`, `nixpkgs-23.05-darwin`, `nixpkgs-unstable`.
    default: true
  ignore-missing-flake-lock:
    description: |
      Whether to ignore a missing `flake.lock` file, where the path to the file is the value of
      `flake-lock-path` parameter. If set to `false` (the default is `true`), the Action throws
      an error and the job fails if the lockfile is missing.
    default: true
  nixpkgs-keys:
    description: |
      The names of the Nixpkgs inputs you want to check. By default the checker only checks the
      `nixpkgs` but you can specify multiple names as a comma-separated list, such as
      `nixpkgs,nixpkgs-macos,nixpkgs-unstable`.
    default: nixpkgs
  fail-mode:
    description: Fail with an exit code of 1 if any issues are encountered.
    default: false
  send-statistics:
    description: |
      Anonymously report the number of issues detected by the Nix Flake Checker. This reporting helps
      measure (and thereby improve) the effectiveness of the checker. Set to `false` to disable.
    default: true
  source-binary:
    description: |
      Run a version of flake-checker from somewhere already on disk. Intended only for testing the Action.
    required: false
  _internal-strict-mode:
    description: Whether to fail when any errors are thrown. Used only to test the Action; do not set this in your own workflows.
    required: false
    default: false
runs:
  using: "node20"
  main: "dist/index.js"
