name: Nix Flake Checker
description: |
  Check your `flake.lock` files for common problems like outdated Nixpkgs releases.
branding:
  icon: "box"
  color: "purple"
inputs:
  flake-lock-path:
    description: |
      The path to the `flake.lock` file you want to check.
    default: flake.lock
  check-outdated:
    description: |
      Whether to check that the root Nixpkgs input is less than 30 days old.
    default: true
  check-owner:
    description: |
      Whether to check that the root Nixpkgs input has the `NixOS` GitHub org as its owner.
    default: true
  check-supported:
    description: |
      Whether to check that the root Nixpkgs input has a supported Git ref. Currently supported
      refs: `nixos-22.11`, `nixos-22.11-small`, `nixos-23.05`, `nixos-23.05-small`, `nixos-unstable`,
      `nixos-unstable-small`, `nixpkgs-22.11-darwin`, `nixpkgs-23.05-darwin`, `nixpkgs-unstable`.
    default: true
  ignore-missing-flake-lock:
    description: |
      Whether to ignore a missing `flake.lock` file, where the path to the file is the value of
      `flake-lock-path` parameter. If set to `false` (the default is `true`), the Action throws
      an error and the job fails if the lockfile is missing.
    default: true
  fail-mode:
    description: Fail with an exit code of 1 if any issues are encountered.
    default: false
  send-statistics:
    description: |
      Anonymously report the number of issues detected by the Nix Flake Checker. This reporting helps
      measure (and thereby improve) the effectiveness of the checker. Set to `false` to disable.
    default: true
runs:
  using: composite
  steps:
    - name: Install the flake checker
      shell: bash
      run: |
        (
          set -eu

          curl --max-time 2 --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/flake-checker/stable/$RUNNER_ARCH-$RUNNER_OS > "$RUNNER_TEMP/flake-checker"
          chmod +x "$RUNNER_TEMP/flake-checker"

          export NIX_FLAKE_CHECKER_FLAKE_LOCK_PATH="${{ inputs.flake-lock-path }}"

          if [ "${{ inputs.send-statistics }}" == "false" ]; then
            export NIX_FLAKE_CHECKER_NO_TELEMETRY="false"
          fi

          if [ "${{ inputs.check-outdated }}" == "false" ]; then
            export NIX_FLAKE_CHECKER_CHECK_OUTDATED="false"
          fi

          if [ "${{ inputs.check-owner }}" == "false" ]; then
            export NIX_FLAKE_CHECKER_CHECK_OWNER="false"
          fi

          if [ "${{ inputs.check-supported }}" == "false" ]; then
            export NIX_FLAKE_CHECKER_CHECK_SUPPORTED="false"
          fi

          if [ "${{ inputs.ignore-missing-flake-lock }}" == "false" ]; then
            export NIX_FLAKE_CHECKER_IGNORE_MISSING_FLAKE_LOCK="false"
          fi

          if [ "${{ inputs.fail-mode }}" == "true" ]; then
            export NIX_FLAKE_CHECKER_FAIL_MODE="true"
          fi

          "$RUNNER_TEMP/flake-checker"
        ) || true
