name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-x86_64-linux-clean:
    name: Run x86_64 Linux (clean)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@fixup
      - name: Check flake.lock
        uses: ./
        with:
          _internal-strict-mode: true
      - run: |
          echo 'int main() { *(volatile int *)0 = 0; }' > test.c
          gcc ./test.c
          ./a.out || true
