name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-x86_64-linux:
    name: Run x86_64 Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: ./

  run-x86_64-darwin:
    name: Run x86_64 Darwin
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: ./
