name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-x86_64-linux-clean:
    name: Run x86_64 Linux (clean)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          _internal-strict-mode: true
