name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-dist-up-to-date:
    name: Check the dist/ folder is up to date
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command pnpm install
      - run: nix develop --command pnpm run format
      - run: nix develop --command pnpm run lint
      - run: nix develop --command pnpm run build
      - run: nix develop --command pnpm run package
      - run: git status --porcelain=v1
      - run: test $(git status --porcelain=v1 2>/dev/null | wc -l) -eq 0

  run-x86_64-linux-clean:
    name: Run x86_64 Linux (clean)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./

  run-x86_64-linux-dirty:
    name: Run x86_64 Linux (dirty)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          flake-lock-path: flake.dirty.lock

  run-x86_64-darwin-clean:
    name: Run x86_64 Darwin (clean)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./

  run-x86_64-darwin-dirty:
    name: Run x86_64 Darwin (dirty)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          flake-lock-path: flake.dirty.lock
