name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-x86_64-linux-clean:
    name: Run x86_64 Linux (clean)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: ./

  run-x86_64-linux-dirty:
    name: Run x86_64 Linux (dirty)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: ./
        with:
          flake-lock-path: flake.dirty.lock

  run-x86_64-darwin-clean:
    name: Run x86_64 Darwin (clean)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: ./

  run-x86_64-darwin-dirty:
    name: Run x86_64 Darwin (dirty)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Check flake.lock
        uses: ./
        with:
          flake-lock-path: flake.dirty.lock
