name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-check-typescript:
    name: Build and check the TypeScript Action
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop --command pnpm install
      - run: nix develop --command pnpm run format
      - run: nix develop --command pnpm run lint
      - run: nix develop --command pnpm run build
      - run: nix develop --command pnpm run package
      - run: git status --porcelain=v1
      - run: git diff --exit-code

  run-x86_64-linux-clean:
    name: Run x86_64 Linux (clean)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          _internal-strict-mode: true
