name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-check-typescript:
    name: Build and check the TypeScript Action
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command pnpm install
      - run: nix develop --command pnpm run format
      - run: nix develop --command pnpm run lint
      - run: nix develop --command pnpm run build
      - run: nix develop --command pnpm run package
      - run: git status --porcelain=v1
      - run: git diff --exit-code

  run-x86_64-linux-clean:
    name: Run x86_64 Linux (clean)
    needs: build-check-typescript
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          _internal-strict-mode: true

  run-x86_64-linux-dirty:
    name: Run x86_64 Linux (dirty)
    needs: build-check-typescript
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          flake-lock-path: flake.dirty.lock
          _internal-strict-mode: true

  run-x86_64-darwin-clean:
    name: Run x86_64 Darwin (clean)
    needs: build-check-typescript
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          _internal-strict-mode: true

  run-x86_64-darwin-dirty:
    name: Run x86_64 Darwin (dirty)
    needs: build-check-typescript
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Check flake.lock
        uses: ./
        with:
          flake-lock-path: flake.dirty.lock
          _internal-strict-mode: true
